#!/usr/bin/env python3

import argparse
import os
import sys

from subprocess import Popen, PIPE

from dpkg import env

parser = argparse.ArgumentParser(
    description='Generate orig.tar.gz from upstream source tree')
args = parser.parse_args()

# basically: dh_testdir
if not os.path.exists('debian/control'):
    print('debian/control: No such file or directory.', file=sys.stderr)
    sys.exit(1)

#git archive --prefix=cgabackup-2.2/ upstream/2.2 | gzip > ../test
pkg = env.get_source_package()
version = env.get_version()['version']

filename = '../%s_%s.orig.tar.gz' % (pkg, version)
prefix = '%s-%s/' % (pkg, version)
tag = 'upstream/%s' % version

f = open(filename, 'w')

archive_cmd = ['git', 'archive', '--prefix=%s' % prefix, tag]
p1 = Popen(archive_cmd, stdout=PIPE)
p2 = Popen('gzip', stdin=p1.stdout, stdout=f)
p1.stdout.close()
p2.communicate()
