#!/bin/bash

set -e

# pull upstream master-branch
git checkout upstream
git pull --tags upstream master

# push upstream branch to origin
git push origin upstream

# merge upstream branch into local master branch
git checkout master
git merge upstream

# push merged debian branch
git push origin master
